// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKw-802iX35gd7bs_mScuABNwNl8F6-Xc',
    appId: '1:763158574833:web:c31a788efbeccf4592db50',
    messagingSenderId: '763158574833',
    projectId: 'footbal-picker',
    authDomain: 'footbal-picker.firebaseapp.com',
    storageBucket: 'footbal-picker.firebasestorage.app',
    measurementId: 'G-L184FYSLJJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEYg00sXlbPSRnvu_OIP1jA6wCzOdNBEM',
    appId: '1:763158574833:android:9de96db880c091e392db50',
    messagingSenderId: '763158574833',
    projectId: 'footbal-picker',
    storageBucket: 'footbal-picker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ6HKsfoz-dShp1b_JVP4AZKFNATRw0o4',
    appId: '1:763158574833:ios:a518e8bd526ec58392db50',
    messagingSenderId: '763158574833',
    projectId: 'footbal-picker',
    storageBucket: 'footbal-picker.firebasestorage.app',
    iosBundleId: 'com.example.footballPicker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQ6HKsfoz-dShp1b_JVP4AZKFNATRw0o4',
    appId: '1:763158574833:ios:a518e8bd526ec58392db50',
    messagingSenderId: '763158574833',
    projectId: 'footbal-picker',
    storageBucket: 'footbal-picker.firebasestorage.app',
    iosBundleId: 'com.example.footballPicker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKw-802iX35gd7bs_mScuABNwNl8F6-Xc',
    appId: '1:763158574833:web:ea59bdf055db0d5d92db50',
    messagingSenderId: '763158574833',
    projectId: 'footbal-picker',
    authDomain: 'footbal-picker.firebaseapp.com',
    storageBucket: 'footbal-picker.firebasestorage.app',
    measurementId: 'G-FPBMRXQL3E',
  );
}
